import React from 'react'
import Head from 'next/head'
import styles from '@component/styles/Home.module.css'


export default function Home() {
  return (
    <>
      <Head>
        <title>Alura Cases - NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>meu primeiro projeto em nextJS</h1>
        </div>
      </main>
    </>
  )
}
